export const images = {
  hero: {
    student: "/assets/hero/hero-student.png",
  },
  people: {
    studentLaptop: "/assets/people/student-laptop.png",
    studentTablet: "/assets/people/student-tablet.png",
  },
  icons: {
    checkCircle: "/assets/icons/check-circle.png",
  },
  testimonials: {
    sarah: "/assets/testimonials/sarah.png",
    james: "/assets/testimonials/james.png",
    alex: "/assets/testimonials/alex.png",
  },
  avatars: [
    "/assets/avatars/avatar-1.png",
    "/assets/avatars/avatar-3.png",
    "/assets/avatars/avatar-4.png",
    "/assets/avatars/avatar-5.png",
    "/assets/avatars/avatar-6.png",
    "/assets/avatars/avatar-7.png",
    "/assets/avatars/avatar-8.png",
  ],
  enrolledAvatars: [
    "/assets/avatars/avatar-3.png",
    "/assets/avatars/avatar-6.png",
    "/assets/testimonials/sarah.png",
    "/assets/testimonials/alex.png",
  ],
  partners: [
    { src: "/assets/partners/partner-2.png", width: 167, height: 41 },
    { src: "/assets/partners/partner-3.png", width: 168, height: 41 },
    { src: "/assets/partners/partner-4.png", width: 170, height: 41 },
    { src: "/assets/partners/partner-5.png", width: 170, height: 41 },
    { src: "/assets/partners/partner-1.png", width: 169, height: 42 },
  ],
  courses: {
    figma: "/assets/courses/course-figma.jpg",
    digitalAsset: "/assets/courses/course-digital-asset.jpg",
    bigData: "/assets/courses/course-big-data.jpg",
    productivity: "/assets/courses/course-productivity.jpg",
    money: "/assets/courses/course-money.jpg",
    startup: "/assets/courses/course-startup.jpg",
  },
  previews: {
    digitalAsset: "/assets/previews/build-digital-asset.jpg",
  },
  sneakPeek: {
    digitalAsset: [
      "/assets/sneak-peek/digital-asset-1.jpg",
      "/assets/sneak-peek/digital-asset-2.jpg",
      "/assets/sneak-peek/digital-asset-3.jpg",
      "/assets/sneak-peek/digital-asset-4.jpg",
    ],
  },
  creators: {
    purepearlStudio: "/assets/creators/purepearl-studio.png",
    purepearlStudioPortrait: "/assets/creators/purepearl-studio-portrait.png",
    northwindAcademy: "/assets/creators/northwind-academy.png",
    pixelPineStudio: "/assets/creators/pixel-pine-studio.png",
    lumenLabs: "/assets/creators/lumen-labs.png",
    bluebirdSchool: "/assets/creators/bluebird-school.png",
  },
  reviewers: {
    purepearlStudio: "/assets/reviewers/purepearl-studio.png",
    albertFlores: "/assets/reviewers/albert-flores.png",
    codyFisher: "/assets/reviewers/cody-fisher.png",
    brooklynSimmons: "/assets/reviewers/brooklyn-simmons.png",
  },
  categories: {
    design: "/assets/categories/design.png",
    development: "/assets/categories/development.png",
    itSoftware: "/assets/categories/it-software.png",
    business: "/assets/categories/business.png",
    marketing: "/assets/categories/marketing.png",
    photography: "/assets/categories/photography.png",
  },
  shapes: {
    cylinderWhite: "/assets/shapes/cylinder-white.png",
    torusLime: "/assets/shapes/torus-lime.png",
    pyramidLime: "/assets/shapes/pyramid-lime.png",
    coneWhite: "/assets/shapes/cone-white.png",
    springLime: "/assets/shapes/spring-lime.png",
    springLimeEdge: "/assets/shapes/spring-lime-edge.png",
    springWhite: "/assets/shapes/spring-white.png",
    springWhiteTilted: "/assets/shapes/spring-white-tilted.png",
    springLimeFlat: "/assets/shapes/spring-lime-flat.png",
    springLimeUpright: "/assets/shapes/spring-lime-upright.png",
    cylinderLime: "/assets/shapes/cylinder-lime.png",
    pyramidWhite: "/assets/shapes/pyramid-white.png",
    torusWhite: "/assets/shapes/torus-white.png",
    torusLimeRing: "/assets/shapes/torus-lime-ring.png",
  },
} as const;
