export const images = {
  hero: {
    student: "/images/hero/hero-student.png",
  },
  people: {
    studentLaptop: "/images/people/student-laptop.png",
    studentTablet: "/images/people/student-tablet.png",
  },
  icons: {
    checkCircle: "/images/icons/check-circle.png",
  },
  testimonials: {
    sarah: "/images/testimonials/sarah.png",
    james: "/images/testimonials/james.png",
    alex: "/images/testimonials/alex.png",
  },
  avatars: [
    "/images/avatars/avatar-1.png",
    "/images/avatars/avatar-3.png",
    "/images/avatars/avatar-4.png",
    "/images/avatars/avatar-5.png",
    "/images/avatars/avatar-6.png",
    "/images/avatars/avatar-7.png",
    "/images/avatars/avatar-8.png",
  ],
  enrolledAvatars: [
    "/images/avatars/avatar-3.png",
    "/images/avatars/avatar-6.png",
    "/images/testimonials/sarah.png",
    "/images/testimonials/alex.png",
  ],
  partners: [
    { src: "/images/partners/partner-2.png", width: 167, height: 41 },
    { src: "/images/partners/partner-3.png", width: 168, height: 41 },
    { src: "/images/partners/partner-4.png", width: 170, height: 41 },
    { src: "/images/partners/partner-5.png", width: 170, height: 41 },
    { src: "/images/partners/partner-1.png", width: 169, height: 42 },
  ],
  courses: {
    figma: "/images/courses/course-figma.jpg",
    digitalAsset: "/images/courses/course-digital-asset.jpg",
    bigData: "/images/courses/course-big-data.jpg",
    productivity: "/images/courses/course-productivity.jpg",
    money: "/images/courses/course-money.jpg",
    startup: "/images/courses/course-startup.jpg",
  },
  previews: {
    digitalAsset: "/images/previews/build-digital-asset.jpg",
  },
  creators: {
    purepearlStudio: "/images/creators/purepearl-studio.png",
    northwindAcademy: "/images/creators/northwind-academy.png",
    pixelPineStudio: "/images/creators/pixel-pine-studio.png",
    lumenLabs: "/images/creators/lumen-labs.png",
    bluebirdSchool: "/images/creators/bluebird-school.png",
  },
  categories: {
    design: "/images/categories/design.png",
    development: "/images/categories/development.png",
    itSoftware: "/images/categories/it-software.png",
    business: "/images/categories/business.png",
    marketing: "/images/categories/marketing.png",
    photography: "/images/categories/photography.png",
  },
  shapes: {
    cylinderWhite: "/images/shapes/cylinder-white.png",
    torusLime: "/images/shapes/torus-lime.png",
    pyramidLime: "/images/shapes/pyramid-lime.png",
    coneWhite: "/images/shapes/cone-white.png",
    springLime: "/images/shapes/spring-lime.png",
    springLimeEdge: "/images/shapes/spring-lime-edge.png",
    springWhite: "/images/shapes/spring-white.png",
    springWhiteTilted: "/images/shapes/spring-white-tilted.png",
    springLimeFlat: "/images/shapes/spring-lime-flat.png",
    springLimeUpright: "/images/shapes/spring-lime-upright.png",
    cylinderLime: "/images/shapes/cylinder-lime.png",
    pyramidWhite: "/images/shapes/pyramid-white.png",
    torusWhite: "/images/shapes/torus-white.png",
  },
} as const;
